# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField()),
                ('odds', models.DecimalField(decimal_places=999, max_digits=999)),
                ('item_link', models.TextField()),
                ('referral_link', models.TextField()),
                ('value', models.DecimalField(decimal_places=999, max_digits=999)),
            ],
        ),
    ]
