# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0002_auto_20170424_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giveaway.Category'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='winner_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
