# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_auto_20170423_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
