# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0004_auto_20170424_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
