# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0005_auto_20170424_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('winner', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='giveaway',
            name='winner_email_address',
        ),
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='entry',
            name='giveaway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway.Giveaway'),
        ),
    ]
