# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0006_auto_20170430_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveaway',
            name='odds',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='max_roll_number',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='number_of_rolls',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
